### ISSUE TITLE
Does this work for games with kernel level anti cheats

### ISSUE THREAD

**Issue by notmentaloutlaw** [lennard0711/vfio#1]
I was wondering if with this setup you got games such as valorant to work. I have tried in the past but the most I have got was a BSOD loop.

**Comment by lennard0711** [comment]
My latest info is, that Valorant will not work with any VFIO setup. Other kernel level anti cheats could work but may not. But if you ask at [r/vfio](https://reddit.com/r/vfio)

For example: [Playing Games with anti-cheat mechanisms on a cloud VM](https://www.reddit.com/r/VFIO/comments/122qyc0/playing_games_with_anticheat_mechanisms_on_a/)
